### PR TITLE
Add Authorization rules for Users

### PR DESCRIPTION
**Pull request by jkanyi-web**
Installed CanCanCan in my project.
Added a role column to the users table. Used a migration for this.
Ensured a user can delete a post if it is theirs or if they have an admin role (column role has value "admin"). Used CanCanCan for this authorization.
Implemented the post deleting functionality. Added the "Delete" button to the view and made sure that only authorized users can see it.
Ensured a user can delete a comment if it is theirs or if they have an admin role (column role has value "admin"). Used CanCanCan for this authorization.
Implemented the comment deleting functionality. Added the "Delete" button to the view and made sure that only authorized users can see it.

### CODE REVIEW

**Review by julie-ify — COMMENTED** [review]
Hi @jkanyi-web and @patriciachrysy,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly submit the PR where changes were requested on. I believe that is this on @patriciachrysy's repository: https://github.com/patriciachrysy/Kdrama-Lovers-Blog/pull/12

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jkanyi-web** [comment]
Hi @julie-ify . I thought the same and that was the original plan but on a pull request yesterday, a reviewer suggested that he could not continue with the review coz this project requires that team individuals submit their requests individually, although it should still be a team project. Kindly refer to this review and confirm the same: https://github.com/jkanyi-web/Blog-App/pull/10

**Comment by Reem-lab** [comment]
Hello @jkanyi-web I saw your note but I couldn't understand the issue please could you tell explain to me?

**Comment by jkanyi-web** [comment]
Hi Reem. Please invalidate that code review I sent, I thought that the same thing happening in a previous review(all individuals in a team collaboration to create review requests individually. Refer to the following review: https://github.com/jkanyi-web/Blog-App/pull/10#pullrequestreview-1777576531) was also applicable in this one. I have confirmed that this is not the case for this part of the project. I apologize for any inconvenience caused.

**Review by Reem-lab — COMMENTED** [review]
Hi @jkanyi-web, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the project is already should be done in one repository so you already submit your partner's PR so you don't need to submit your PR you just can work on his repo 🔥🚀


image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
